### ISSUE TITLE
Tokenize in clean_text()

### ISSUE THREAD

**Issue by nhubert** [xssChauhan/Blog-Posts#2]
Hello,

Thank you for you blog post.

Where do you tokenize the data inside the clean_text() function ?

```
def clean_text(df):
    '''
    Take in a Dataframe, and process it
    '''
    df["cleaned_text"] = df.text.map(lambda text:text.lower()).map(remove_emails).map(remove_newlinechars).map(remove_stopwords).map(lemmatize)
    return df
```

**Comment by xssChauhan** [comment]
Hello @nhubert, good catch. I think the `clean_text` function is not used in the final cleaning. But the `lemmatize` function takes care of the tokenization anyways.
